/* JAL shared header and Ally accessibility assistant. */
(function () {
  'use strict';
  const nav = [
    ['Our Story', 'index.html'], ['Products', 'products.html'], ['Services', 'services.html'],
    ['Arduino', 'arduino.html'], ['Projects', 'projects.html'], ['Team', 'team.html'],
    ['Insights', 'insights.html'], ['Get Quote', 'quote.html'], ['Contacts', 'contact.html']
  ];
  const page = location.pathname.split('/').pop() || 'index.html';
  const prefKey = 'jal-ally-prefs';
  const defaults = { contrast:false, dark:false, gray:false, dyslexia:false, spacing:false, guide:false, links:false, focus:false, motion:false, scale:1, line:1.65 };
  let prefs = defaults;
  try { prefs = Object.assign({}, defaults, JSON.parse(localStorage.getItem(prefKey) || '{}')); } catch (_) {}
  const save = () => { try { localStorage.setItem(prefKey, JSON.stringify(prefs)); } catch (_) {} };

  const style = document.createElement('style');
  style.textContent = `
    .topnav, header.topnav { display:none!important; }
    .jal-header { position:sticky; top:0; z-index:9000; background:rgba(255,253,249,.95); backdrop-filter:blur(16px); border-bottom:1px solid rgba(31,43,36,.1); font-family:'DM Sans',sans-serif; }
    .jal-header-inner { width:min(1240px,calc(100% - 32px)); min-height:74px; margin:auto; display:flex; align-items:center; gap:1rem; }
    .jal-brand { display:flex; align-items:center; gap:.65rem; flex-shrink:0; text-decoration:none; }
    .jal-brand img { width:52px; height:52px; object-fit:contain; }
    .jal-brand span { display:flex; flex-direction:column; line-height:1; }
    .jal-brand b { color:#1f6b4d; font:700 1.42rem 'Dancing Script',cursive; }
    .jal-brand small { margin-top:.24rem; color:#e79a42; font:800 .56rem 'Syne',sans-serif; letter-spacing:.13em; text-transform:uppercase; }
    .jal-nav { margin-left:auto; }.jal-nav ul { display:flex; align-items:center; gap:clamp(.55rem,1.05vw,1rem); list-style:none; margin:0; padding:0; }.jal-nav a { position:relative; display:inline-flex; padding:.48rem 0; color:#4d5a54; font-size:.7rem; font-weight:800; letter-spacing:.075em; text-transform:uppercase; }.jal-nav a:after { content:""; position:absolute; left:18%; right:18%; bottom:.14rem; height:2px; border-radius:99px; background:#e79a42; opacity:0; transform:scaleX(.35); transition:.2s; }.jal-nav a:hover,.jal-nav a:focus-visible,.jal-nav a.active { color:#1f6b4d; }.jal-nav a:hover:after,.jal-nav a:focus-visible:after,.jal-nav a.active:after { opacity:1; transform:scaleX(1); }.jal-nav a.quote { padding:.68rem .92rem; border-radius:999px; color:#fff; background:linear-gradient(135deg,#1f6b4d,#2e8d69); }.jal-nav a.quote:after { display:none; }
    .jal-menu { display:none; margin-left:auto; border:0; background:transparent; color:#124733; font-size:1.5rem; cursor:pointer; padding:.45rem; }
    @media(max-width:980px){.jal-menu{display:block}.jal-nav{position:fixed;inset:74px 0 auto 0;padding:.8rem 1.25rem 1.3rem;background:#fffdf9;border-bottom:1px solid rgba(31,43,36,.1);box-shadow:0 18px 30px rgba(18,35,29,.1);transform:translateY(-130%);transition:transform .25s ease}.jal-nav.open{transform:translateY(0)}.jal-nav ul{display:grid;gap:.1rem}.jal-nav a{width:100%;padding:.7rem .25rem;font-size:.78rem}.jal-nav a.quote{text-align:center;justify-content:center;margin-top:.35rem}}
    #jal-whatsapp { position:fixed; right:1.25rem; bottom:1.25rem; z-index:9500; width:3.65rem; height:3.65rem; display:grid; place-items:center; border-radius:50%; color:#fff; background:#25d366; box-shadow:0 10px 25px rgba(37,211,102,.3); } #jal-whatsapp svg{width:1.75rem;height:1.75rem;fill:currentColor}
    #jal-ally-toggle { position:fixed; left:0; top:50%; z-index:99998; width:48px; height:48px; border:0; border-radius:0 14px 14px 0; color:#fff; background:#2f855a; cursor:pointer; font-size:1.2rem; box-shadow:3px 4px 18px rgba(0,0,0,.22); }
    #jal-ally-overlay { position:fixed; inset:0; z-index:99997; background:rgba(8,16,14,.35); opacity:0; visibility:hidden; } #jal-ally-overlay.open{opacity:1;visibility:visible}
    #jal-ally-panel { position:fixed; left:0; top:0; z-index:99999; width:min(350px,92vw); height:100vh; padding:1rem; overflow:auto; color:#102a24; background:#fffdf9; box-shadow:6px 0 35px rgba(0,0,0,.2); transform:translateX(-105%); transition:transform .25s ease; font-family:'DM Sans',sans-serif; } #jal-ally-panel.open{transform:translateX(0)}
    .ally-head{display:flex;align-items:center;gap:.7rem;padding-bottom:.9rem;border-bottom:1px solid rgba(16,42,36,.1)}.ally-head img{width:42px;height:42px;object-fit:contain}.ally-head h2{margin:0;font:800 1.05rem 'Syne',sans-serif}.ally-head small{display:block;color:#56615c;margin-top:.15rem}.ally-close{margin-left:auto!important;border:0!important;background:transparent!important;font-size:1.2rem!important}.ally-group{margin-top:1rem}.ally-group h3{margin:0 0 .45rem;color:#2f855a;font-size:.68rem;letter-spacing:.14em;text-transform:uppercase}.ally-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.45rem}.ally-btn{margin:0;padding:.65rem .55rem;border:1px solid rgba(16,42,36,.13);border-radius:10px;background:#fff;color:#102a24;font-size:.76rem;cursor:pointer}.ally-btn:hover,.ally-btn[aria-pressed=true]{border-color:#2f855a;background:#eaf4ee}.ally-wide{width:100%;margin-top:.55rem}.ally-status{min-height:1.2em;margin-top:.7rem;color:#2f855a;font-size:.78rem}.ally-guide{position:fixed;left:0;right:0;height:3px;z-index:99996;background:#e79a42;box-shadow:0 0 10px rgba(231,154,66,.7);pointer-events:none;display:none}
    html.jal-contrast body{background:#000!important;color:#fff!important}html.jal-contrast a{color:#ffdc73!important;text-decoration:underline!important}html.jal-dark{filter:invert(1) hue-rotate(180deg)}html.jal-gray{filter:grayscale(1)}html.jal-dyslexia *{font-family:'OpenDyslexic','Comic Sans MS',sans-serif!important}html.jal-spacing *{letter-spacing:.08em!important;word-spacing:.14em!important}html.jal-links a{text-decoration:underline!important;background:#fff59d!important;color:#102a24!important}html.jal-focus *:focus-visible{outline:3px solid #ffbf00!important;outline-offset:3px!important}html.jal-motion *,html.jal-motion *:before,html.jal-motion *:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}html.jal-line p,html.jal-line li{line-height:var(--jal-line-height)!important}
  `;
  document.head.appendChild(style);

  const header = document.createElement('header'); header.className = 'jal-header';
  header.innerHTML = `<div class="jal-header-inner"><a class="jal-brand" href="index.html" aria-label="Jengalabs Afritech home"><img src="jal-logo.png" alt="Jengalabs Afritech Limited logo"><span><b>Jengalabs</b><small>Afritech Limited</small></span></a><button class="jal-menu" aria-expanded="false" aria-label="Open navigation">☰</button><nav class="jal-nav" aria-label="Main navigation"><ul>${nav.map(([label, href]) => `<li><a href="${href}" class="${href===page?'active':''}${href==='quote.html'?' quote':''}">${label}</a></li>`).join('')}</ul></nav></div>`;
  document.body.insertBefore(header, document.body.firstChild);
  const menu = header.querySelector('.jal-menu'), navigation = header.querySelector('.jal-nav');
  menu.addEventListener('click', () => { const open = navigation.classList.toggle('open'); menu.textContent = open ? '×' : '☰'; menu.setAttribute('aria-expanded', String(open)); });

  if (page === 'index.html') {
    const whatsapp = document.createElement('a'); whatsapp.id='jal-whatsapp'; whatsapp.href='https://wa.me/254114976187?text=Hi%20Jenga%20Labs%20Afritech'; whatsapp.target='_blank'; whatsapp.rel='noopener'; whatsapp.setAttribute('aria-label','Chat with Jengalabs Afritech on WhatsApp'); whatsapp.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.9 11.9 0 0 0 12 0C5.4 0 .1 5.4.1 11.9c0 2.1.5 4.2 1.6 6L0 24l6.3-1.6a12 12 0 0 0 5.7 1.4h.1c6.5 0 11.9-5.3 11.9-11.9 0-3.2-1.3-6.2-3.5-8.4ZM12 21.8h-.1c-1.8 0-3.5-.5-5.1-1.4l-.4-.2-3.7 1 1-3.6-.2-.4a9.8 9.8 0 0 1-1.5-5.2C2 6.5 6.5 2 12 2c2.7 0 5.2 1 7 2.9a9.9 9.9 0 0 1 2.9 7c0 5.4-4.4 9.9-9.9 9.9Zm5.5-7.3c-.3-.2-1.8-.9-2-.9-.3-.1-.5-.2-.7.1-.2.3-.8 1-.9 1.2-.2.2-.4.2-.7.1-1.7-.9-2.9-1.6-4-3.6-.3-.5.3-.5.9-1.7.1-.2.1-.4 0-.6-.1-.2-.7-1.6-.9-2.2-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.2-.3-.3-.7-.5Z"/></svg>'; document.body.appendChild(whatsapp);
    document.querySelectorAll('a').forEach(link => { if (link.textContent.trim().toLowerCase() === 'talk to us') link.href = 'contact.html'; });
  }

  const toggle=document.createElement('button'); toggle.id='jal-ally-toggle'; toggle.type='button'; toggle.textContent='♿'; toggle.setAttribute('aria-label','Open Ally accessibility assistant');
  const overlay=document.createElement('div'); overlay.id='jal-ally-overlay';
  const panel=document.createElement('aside'); panel.id='jal-ally-panel'; panel.setAttribute('aria-label','Ally accessibility assistant'); panel.innerHTML=`<div class="ally-head"><img src="jal-logo.png" alt="JAL Ally logo"><div><h2>Ally assistant</h2><small>Make JAL work for you</small></div><button class="ally-close" data-action="close" aria-label="Close assistant">×</button></div><div class="ally-group"><h3>Vision</h3><div class="ally-grid"><button class="ally-btn" data-key="contrast">High contrast</button><button class="ally-btn" data-key="dark">Dark mode</button><button class="ally-btn" data-key="gray">Grayscale</button></div></div><div class="ally-group"><h3>Reading</h3><div class="ally-grid"><button class="ally-btn" data-key="dyslexia">Dyslexia font</button><button class="ally-btn" data-key="spacing">Text spacing</button><button class="ally-btn" data-key="guide">Reading guide</button><button class="ally-btn" data-key="links">Highlight links</button></div><button class="ally-btn ally-wide" data-step="scale" data-dir="-1">A− Smaller text</button><button class="ally-btn ally-wide" data-step="scale" data-dir="1">A+ Larger text</button><button class="ally-btn ally-wide" data-step="line" data-dir="1">↕ Increase line spacing</button></div><div class="ally-group"><h3>Navigation</h3><div class="ally-grid"><button class="ally-btn" data-key="focus">Focus ring</button><button class="ally-btn" data-key="motion">Stop motion</button></div></div><div class="ally-group"><h3>Voice assist</h3><div class="ally-grid"><button class="ally-btn" data-action="read">🔊 Read page</button><button class="ally-btn" data-action="stop">■ Stop reading</button></div></div><button class="ally-btn ally-wide" data-action="reset">Reset settings</button><div class="ally-status" role="status" aria-live="polite"></div>`;
  const guide=document.createElement('div'); guide.className='ally-guide'; document.body.append(toggle,overlay,panel,guide);
  const status = message => { panel.querySelector('.ally-status').textContent = message; };
  const apply = () => { const root=document.documentElement; [['contrast','jal-contrast'],['dark','jal-dark'],['gray','jal-gray'],['dyslexia','jal-dyslexia'],['spacing','jal-spacing'],['links','jal-links'],['focus','jal-focus'],['motion','jal-motion']].forEach(([key,cls])=>root.classList.toggle(cls,!!prefs[key])); root.style.fontSize = `${prefs.scale*100}%`; root.style.setProperty('--jal-line-height', prefs.line); root.classList.toggle('jal-line', prefs.line !== defaults.line); guide.style.display = prefs.guide ? 'block' : 'none'; panel.querySelectorAll('[data-key]').forEach(btn=>btn.setAttribute('aria-pressed',String(!!prefs[btn.dataset.key])) }; 
  const open=()=>{panel.classList.add('open');overlay.classList.add('open');toggle.setAttribute('aria-expanded','true')}; const close=()=>{panel.classList.remove('open');overlay.classList.remove('open');toggle.setAttribute('aria-expanded','false')}; toggle.setAttribute('aria-expanded','false'); toggle.onclick=open; overlay.onclick=close;
  panel.onclick = event => { const btn=event.target.closest('button'); if(!btn)return; if(btn.dataset.action==='close')return close(); if(btn.dataset.action==='reset'){prefs={...defaults};save();apply();return status('Settings reset.')} if(btn.dataset.action==='read'){if('speechSynthesis' in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(document.body.innerText));status('Reading this page aloud.')}return} if(btn.dataset.action==='stop'){if('speechSynthesis' in window)speechSynthesis.cancel();return status('Reading stopped.')} if(btn.dataset.key){prefs[btn.dataset.key]=!prefs[btn.dataset.key];save();apply();return} if(btn.dataset.step){const key=btn.dataset.step;const amount=key==='scale'?.1:.1;const min=key==='scale'?.8:1.65;const max=key==='scale'?1.5:2.4;prefs[key]=Math.max(min,Math.min(max,Number((prefs[key]+Number(btn.dataset.dir)*amount).toFixed(2))));save();apply();status('Reading settings updated.')}};
  document.addEventListener('mousemove',event=>{if(prefs.guide)guide.style.top=`${event.clientY}px`}); document.addEventListener('keydown',event=>{if(event.key==='Escape')close()}); apply();
})();
