/* JAL shared header, WhatsApp contact and minimal accessibility assistant. */
(function () {
  const nav = [
    ['Our Story', 'index.html'], ['Products', 'products.html'], ['Services', 'services.html'],
    ['Arduino', 'arduino.html'], ['Projects', 'projects.html'], ['Team', 'team.html'],
    ['Insights', 'insights.html'], ['Get Quote', 'quote.html'], ['Contacts', 'contact.html']
  ];
  const current = location.pathname.split('/').pop() || 'index.html';
  const prefsKey = 'jal-a11y-prefs-v3';
  const defaults = { contrast:false, dark:false, grayscale:false, dyslexia:false, spacing:false, guide:false, links:false, focus:false, cursor:false, motion:false, scale:1, line:1.65 };
  let prefs;
  try { prefs = Object.assign({}, defaults, JSON.parse(localStorage.getItem(prefsKey) || '{}')); } catch (_) { prefs = {...defaults}; }
  const save = () => { try { localStorage.setItem(prefsKey, JSON.stringify(prefs)); } catch (_) {} };

  const header = document.createElement('header');
  header.className = 'jal-shared-header';
  header.innerHTML = `<div class="jal-header-inner">
    <a class="jal-brand" href="index.html" aria-label="Jengalabs Afritech home"><img src="jal-logo.png" alt="Jengalabs Afritech Limited logo"><span><b>Jengalabs</b><small>Afritech Limited</small></span></a>
    <button class="jal-menu-button" type="button" aria-expanded="false" aria-controls="jal-navigation" aria-label="Open navigation">☰</button>
    <nav id="jal-navigation" aria-label="Main navigation"><ul>${nav.map(([label, href]) => `<li><a href="${href}" class="${href === current ? 'active' : ''}${href === 'quote.html' ? ' quote' : ''}">${label}</a></li>`).join('')}</ul></nav>
  </div>`;

  const style = document.createElement('style');
  style.textContent = `
    .topnav,header.topnav{display:none!important}.jal-shared-header{position:sticky;top:0;z-index:9000;background:rgba(255,253,249,.94);backdrop-filter:blur(16px);border-bottom:1px solid rgba(31,43,36,.1);font-family:'DM Sans',sans-serif}.jal-header-inner{width:min(1240px,calc(100% - 32px));min-height:74px;margin:auto;display:flex;align-items:center;gap:1rem}.jal-brand{display:inline-flex;align-items:center;gap:.65rem;color:#1f2b24;text-decoration:none;flex-shrink:0}.jal-brand img{width:52px;height:52px;object-fit:contain}.jal-brand span{display:flex;flex-direction:column;line-height:1}.jal-brand b{color:#1f6b4d;font:700 1.42rem 'Dancing Script',cursive}.jal-brand small{margin-top:.24rem;color:#e79a42;font:800 .56rem 'Syne',sans-serif;letter-spacing:.13em;text-transform:uppercase}#jal-navigation{margin-left:auto}#jal-navigation ul{display:flex;align-items:center;gap:clamp(.55rem,1.05vw,1rem);list-style:none;margin:0;padding:0}#jal-navigation a{position:relative;display:inline-flex;padding:.48rem 0;color:#4d5a54;text-decoration:none;font-size:.7rem;font-weight:800;letter-spacing:.075em;text-transform:uppercase}#jal-navigation a:after{content:"";position:absolute;left:18%;right:18%;bottom:.14rem;height:2px;border-radius:99px;background:#e79a42;opacity:0;transform:scaleX(.35);transition:.2s}#jal-navigation a:hover,#jal-navigation a:focus-visible,#jal-navigation a.active{color:#1f6b4d}#jal-navigation a:hover:after,#jal-navigation a:focus-visible:after,#jal-navigation a.active:after{opacity:1;transform:scaleX(1)}#jal-navigation a.quote{padding:.68rem .92rem;border-radius:999px;color:#fff;background:linear-gradient(135deg,#1f6b4d,#2e8d69);box-shadow:0 8px 18px rgba(31,107,77,.18)}#jal-navigation a.quote:after{display:none}.jal-menu-button{display:none;margin-left:auto;border:0;background:transparent;color:#124733;font-size:1.5rem;cursor:pointer;padding:.45rem}
    @media(max-width:980px){.jal-menu-button{display:block}#jal-navigation{position:fixed;inset:74px 0 auto 0;padding:.8rem 1.25rem 1.3rem;background:#fffdf9;border-bottom:1px solid rgba(31,43,36,.1);box-shadow:0 18px 30px rgba(18,35,29,.1);transform:translateY(-130%);transition:transform .25s ease}#jal-navigation.open{transform:translateY(0)}#jal-navigation ul{display:grid;gap:.1rem}#jal-navigation a{width:100%;padding:.7rem .25rem;font-size:.78rem}#jal-navigation a.quote{text-align:center;justify-content:center;margin-top:.35rem}}
    .jal-codelab-link{display:inline-flex;margin:1.25rem 1.5rem;padding:.8rem 1.1rem;border-radius:999px;background:#1f6b4d;color:#fff;font-weight:800;text-decoration:none}
    #jal-whatsapp{position:fixed;right:1.25rem;bottom:1.25rem;z-index:9500;width:3.65rem;height:3.65rem;display:grid;place-items:center;border-radius:50%;color:#fff;background:#25d366;box-shadow:0 10px 25px rgba(37,211,102,.3)}#jal-whatsapp svg{width:1.75rem;height:1.75rem;fill:currentColor}
    #jal-a11y-toggle{position:fixed;left:0;top:50%;z-index:99998;width:48px;height:48px;border:0;border-radius:0 14px 14px 0;color:#fff;background:#2f855a;cursor:pointer;font-size:1.2rem;box-shadow:3px 4px 18px rgba(0,0,0,.22)}#jal-a11y-toggle:hover{background:#e79a42}
    #jal-a11y-panel{position:fixed;left:0;top:0;z-index:99999;width:min(350px,92vw);height:100vh;padding:1rem;overflow:auto;color:#102a24;background:#fffdf9;box-shadow:6px 0 35px rgba(0,0,0,.2);transform:translateX(-105%);transition:transform .25s ease}#jal-a11y-panel.open{transform:translateX(0)}.jal-a11y-head{display:flex;align-items:center;gap:.7rem;padding-bottom:.9rem;border-bottom:1px solid rgba(16,42,36,.1)}.jal-a11y-head img{width:42px;height:42px;object-fit:contain}.jal-a11y-head h2{margin:0;font:800 1.05rem 'Syne',sans-serif}.jal-a11y-head small{display:block;color:#56615c;margin-top:.15rem}.jal-a11y-close{margin-left:auto!important;border:0!important;background:transparent!important;font-size:1.2rem!important}.jal-a11y-group{margin-top:1rem}.jal-a11y-group h3{margin:0 0 .45rem;color:#2f855a;font-size:.68rem;letter-spacing:.14em;text-transform:uppercase}.jal-a11y-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.45rem}.jal-a11y-panel-btn{margin:0!important;padding:.65rem .55rem!important;border:1px solid rgba(16,42,36,.13)!important;border-radius:10px!important;background:#fff!important;color:#102a24;font-size:.76rem;cursor:pointer}.jal-a11y-panel-btn:hover,.jal-a11y-panel-btn[aria-pressed=true]{border-color:#2f855a!important;background:#eaf4ee!important}.jal-a11y-wide{width:100%;margin-top:.55rem!important}.jal-a11y-status{min-height:1.2em;margin-top:.7rem;color:#2f855a;font-size:.78rem}.jal-a11y-guide{position:fixed;left:0;right:0;height:3px;z-index:99996;background:#e79a42;box-shadow:0 0 10px rgba(231,154,66,.7);pointer-events:none;display:none}.jal-a11y-overlay{position:fixed;inset:0;z-index:99997;background:rgba(8,16,14,.35);opacity:0;visibility:hidden}.jal-a11y-overlay.open{opacity:1;visibility:visible}
    html.jal-a11y-contrast body{background:#000!important;color:#fff!important}html.jal-a11y-contrast a{color:#ffdc73!important;text-decoration:underline!important}html.jal-a11y-dark{filter:invert(1) hue-rotate(180deg)}html.jal-a11y-gray{filter:grayscale(1)}html.jal-a11y-dyslexia *{font-family:'OpenDyslexic','Comic Sans MS',sans-serif!important}html.jal-a11y-spacing *{letter-spacing:.08em!important;word-spacing:.14em!important}html.jal-a11y-links a{text-decoration:underline!important;background:#fff59d!important;color:#102a24!important}html.jal-a11y-focus *:focus-visible{outline:3px solid #ffbf00!important;outline-offset:3px!important}html.jal-a11y-cursor,html.jal-a11y-cursor *{cursor:crosshair!important}html.jal-a11y-motion *,html.jal-a11y-motion *:before,html.jal-a11y-motion *:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}html.jal-a11y-line p,html.jal-a11y-line li{line-height:var(--jal-a11y-line-height)!important}
    @media(prefers-reduced-motion:reduce){#jal-a11y-panel,#jal-navigation,#jal-navigation a:after{transition:none!important}}
  `;
  document.head.appendChild(style);
  document.body.insertBefore(header, document.body.firstChild);

  if (current === 'arduino.html') { const link = document.createElement('a'); link.className='jal-codelab-link'; link.href='codelab.html'; link.textContent='Open Code Lab →'; header.after(link); }
  const menu=header.querySelector('.jal-menu-button'), navEl=header.querySelector('#jal-navigation');
  menu.addEventListener('click',()=>{const open=navEl.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'×':'☰';});

  if (current === 'index.html') { const whatsapp=document.createElement('a');whatsapp.id='jal-whatsapp';whatsapp.href='https://wa.me/254114976187?text=Hi%20Jenga%20Labs%20Afritech';whatsapp.target='_blank';whatsapp.rel='noopener';whatsapp.setAttribute('aria-label','Chat with Jengalabs Afritech on WhatsApp');whatsapp.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.9 11.9 0 0 0 12 0C5.4 0 .1 5.4.1 11.9c0 2.1.5 4.2 1.6 6L0 24l6.3-1.6a12 12 0 0 0 5.7 1.4h.1c6.5 0 11.9-5.3 11.9-11.9 0-3.2-1.3-6.2-3.5-8.4ZM12 21.8h-.1c-1.8 0-3.5-.5-5.1-1.4l-.4-.2-3.7 1 1-3.6-.2-.4a9.8 9.8 0 0 1-1.5-5.2C2 6.5 6.5 2 12 2c2.7 0 5.2 1 7 2.9a9.9 9.9 0 0 1 2.9 7c0 5.4-4.4 9.9-9.9 9.9Zm5.5-7.3c-.3-.2-1.8-.9-2-.9-.3-.1-.5-.2-.7.1-.2.3-.8 1-.9 1.2-.2.2-.4.2-.7.1-1.7-.9-2.9-1.6-4-3.6-.3-.5.3-.5.9-1.7.1-.2.1-.4 0-.6-.1-.2-.7-1.6-.9-2.2-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.2 5.1 4.5.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.2-.3-.3-.7-.5Z"/></svg>';document.body.appendChild(whatsapp); }

  const toggle=document.createElement('button');toggle.id='jal-a11y-toggle';toggle.type='button';toggle.textContent='♿';toggle.setAttribute('aria-label','Open Ally accessibility assistant');
  const overlay=document.createElement('div');overlay.className='jal-a11y-overlay';
  const panel=document.createElement('aside');panel.id='jal-a11y-panel';panel.setAttribute('aria-label','Ally accessibility assistant');panel.innerHTML=`<div class="jal-a11y-head"><img src="jal-logo.png" alt="JAL Ally logo"><div><h2>Ally assistant</h2><small>Make JAL work for you</small></div><button class="jal-a11y-close" data-a11y="close" aria-label="Close assistant">×</button></div><div class="jal-a11y-group"><h3>Vision</h3><div class="jal-a11y-grid"><button class="jal-a11y-panel-btn" data-key="contrast">High contrast</button><button class="jal-a11y-panel-btn" data-key="dark">Dark mode</button><button class="jal-a11y-panel-btn" data-key="grayscale">Grayscale</button><button class="jal-a11y-panel-btn" data-key="cursor">Large cursor</button></div></div><div class="jal-a11y-group"><h3>Reading</h3><div class="jal-a11y-grid"><button class="jal-a11y-panel-btn" data-key="dyslexia">Dyslexia font</button><button class="jal-a11y-panel-btn" data-key="spacing">Text spacing</button><button class="jal-a11y-panel-btn" data-key="guide">Reading guide</button><button class="jal-a11y-panel-btn" data-key="links">Highlight links</button></div><button class="jal-a11y-panel-btn jal-a11y-wide" data-step="scale" data-dir="-1">A− &nbsp; Smaller text</button><button class="jal-a11y-panel-btn jal-a11y-wide" data-step="scale" data-dir="1">A+ &nbsp; Larger text</button><button class="jal-a11y-panel-btn jal-a11y-wide" data-step="line" data-dir="1">↕ &nbsp; Increase line spacing</button></div><div class="jal-a11y-group"><h3>Navigation</h3><div class="jal-a11y-grid"><button class="jal-a11y-panel-btn" data-key="focus">Focus ring</button><button class="jal-a11y-panel-btn" data-key="motion">Stop motion</button></div></div><div class="jal-a11y-group"><h3>Voice assist</h3><div class="jal-a11y-grid"><button class="jal-a11y-panel-btn" data-a11y="read">🔊 Read page</button><button class="jal-a11y-panel-btn" data-a11y="stop">■ Stop reading</button></div></div><button class="jal-a11y-panel-btn jal-a11y-wide" data-a11y="reset">Reset settings</button><div class="jal-a11y-status" role="status" aria-live="polite"></div>`;
  const guide=document.createElement('div');guide.className='jal-a11y-guide';
  document.body.append(toggle,overlay,panel,guide);
  const status=msg=>{panel.querySelector('.jal-a11y-status').textContent=msg;};
  const apply=()=>{const root=document.documentElement;[['contrast','jal-a11y-contrast'],['dark','jal-a11y-dark'],['grayscale','jal-a11y-gray'],['dyslexia','jal-a11y-dyslexia'],['spacing','jal-a11y-spacing'],['links','jal-a11y-links'],['focus','jal-a11y-focus'],['cursor','jal-a11y-cursor'],['motion','jal-a11y-motion']].forEach(([key,cls])=>root.classList.toggle(cls,!!prefs[key]));root.style.fontSize=`${prefs.scale*100}%`;root.style.setProperty('--jal-a11y-line-height',prefs.line);root.classList.toggle('jal-a11y-line',prefs.line!==defaults.line);guide.style.display=prefs.guide?'block':'none';panel.querySelectorAll('[data-key]').forEach(btn=>btn.setAttribute('aria-pressed',String(!!prefs[btn.dataset.key]))};
  const open=()=>{panel.classList.add('open');overlay.classList.add('open');toggle.setAttribute('aria-expanded','true')};const close=()=>{panel.classList.remove('open');overlay.classList.remove('open');toggle.setAttribute('aria-expanded','false')};toggle.setAttribute('aria-expanded','false');toggle.onclick=open;overlay.onclick=close;
  panel.onclick=e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.a11y==='close')return close();if(btn.dataset.a11y==='reset'){prefs={...defaults};save();apply();return status('Settings reset.')}if(btn.dataset.a11y==='read'){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(document.body.innerText));status('Reading this page aloud.')}return}if(btn.dataset.a11y==='stop'){if('speechSynthesis'in window)speechSynthesis.cancel();return status('Reading stopped.')}if(btn.dataset.key){prefs[btn.dataset.key]=!prefs[btn.dataset.key];save();apply();return}if(btn.dataset.step){const key=btn.dataset.step;const step=key==='scale'?.1:.1;prefs[key]=Math.max(key==='scale'?.8:1.65,Math.min(key==='scale'?1.5:2.4,+(prefs[key]+Number(btn.dataset.dir)*step).toFixed(2)));save();apply();status('Reading settings updated.')}};
  document.addEventListener('mousemove',e=>{if(prefs.guide)guide.style.top=`${e.clientY}px`});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});apply();
})();
